"""empty message

Revision ID: 4f34056f3dfa
Revises: 5f54adb0d963
Create Date: 2018-08-13 17:18:05.489063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f34056f3dfa'
down_revision = '5f54adb0d963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('board', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'board')
    # ### end Alembic commands ###
